# Generated by Django 5.1.4 on 2024-12-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("weight", models.FloatField()),
                ("height", models.FloatField()),
                ("veg_or_nonveg", models.CharField(max_length=20)),
                ("goal", models.CharField(max_length=50)),
                ("disease", models.TextField(blank=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("allergics", models.TextField(blank=True)),
                ("food_type", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DietRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation_text", models.TextField()),
                ("bmi", models.FloatField()),
                ("bmi_category", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userprofile",
                    ),
                ),
            ],
        ),
    ]
