# Generated by Django 5.1.4 on 2024-12-26 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fitnessrecommendation",
            name="recommendation_json",
        ),
        migrations.AddField(
            model_name="fitnessrecommendation",
            name="recommendation_text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
